import a from "./songs/a.mp3";
const SongsData = [
  {
    artist: "unknown",
    src: a,
    songName: "guli mata",
    genre: "pop",
    imgSrc: "https://i.ytimg.com/vi/Gp1RNYBckBs/hqdefault.jpg",
  },
  {
    artist: "atif aslam",
    src: "https://pagalnew.com/download128/19008",
    songName: "Rafta Rafta",
    genre: "pop",
    imgSrc:
      "https://pagalnew.com/coverimages/Rafta-Rafta-Atif-Aslam-500-500.jpg",
  },
  {
    artist: "atif aslam",
    src: "https://pagalnew.com/download128/22849",
    songName: "Sang E Mah",
    genre: "pop",
    imgSrc:
      "https://pagalnew.com/coverimages/sang-e-mah-atif-aslam-500-500.jpg",
  },
  {
    artist: "atif aslam",
    src: "https://pagaliworld.com/files/download/id/15853",
    songName: "Keyse Bataye Kyun Tujhko Chahe",
    genre: "pop",
    imgSrc: "https://www.pagalwrold.com/siteuploads/thumb/sft31/15485_4.jpg",
  },
  {
    artist: "atif aslam",
    src: "https://pagaliworld.com/files/download/id/13873",
    songName: "Woh Lamhe Woh Baatein",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft28/13873_4.jpg",
  },
  {
    artist: "atif aslam",
    src: "https://pagalnew.com/download128/23254",
    songName: "Juda Hoke Bhi Tu Mujhme Kahi Baki Hai",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft27/13280_4.jpg",
  },
  {
    artist: "atif aslam",
    src: "https://pagalnew.com/download128/23296",
    songName: " Agay Dekh",
    genre: "pop",
    imgSrc: "https://pagalnew.com/coverimages/agay-dekh-atif-aslam-500-500.jpg",
  },
  {
    artist: "atif aslam",
    src: "https://pagaliworld.com/files/download/id/11792",
    songName: "Oo Karam Khudaya Ha",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft24/11792_4.jpg",
  },
  {
    artist: "atif aslam",
    src: "https://pagaliworld.com/files/download/id/10299",
    songName: "Moonrise",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft21/10299_4.jpg",
  },
  {
    artist: "atif aslam",
    src: "https://pagaliworld.com/files/download/id/9527",
    songName: "Alvida Ho Gaye Dekhte Dekhte",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft20/9527_4.jpg",
  },
  {
    artist: "atif aslam",
    src: "https://pagaliworld.com/files/download/id/5096",
    songName: "Dil Meri Na Sune",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft11/5096_4.jpg",
  },
  {
    artist: "arijit singh",
    src: "https://pagaliworld.com/files/download/id/16137",
    songName: " Tu Hi Hai Aashiqui Tu Hi Aawargi ",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft33/16137_4.jpg",
  },
  {
    artist: "arijit singh",
    src: "https://pagaliworld.com/files/download/id/15672",
    songName: "pasoori nu",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft32/15672_4.jpg",
  },
  {
    artist: "arijit singh",
    src: "https://pagaliworld.com/files/download/id/15465",
    songName: "Naina",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft31/15465_4.jpg",
  },
  {
    artist: "arijit singh",
    src: "https://pagaliworld.com/files/download/id/13328",
    songName: "Khamoshiyan",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft27/13328_4.jpg",
  },
  {
    artist: "arijit singh",
    src: "https://pagaliworld.com/files/download/id/13366",
    songName: "Main Dhoondne Ko Zamaane Main",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft27/13366_4.jpg",
  },
  {
    artist: "arijit singh",
    src: "https://pagaliworld.com/files/download/id/13089",
    songName: "Tera Fitoor Jab Se Chad Gaya Re",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft27/13089_4.jpg",
  },
  {
    artist: "arijit singh",
    src: "https://pagaliworld.com/files/download/id/12128",
    songName: " Chahun Main Ya Naa",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft25/12128_4.jpg",
  },
  {
    artist: "arijit singh",
    src: "https://pagaliworld.com/files/download/id/11746",
    songName: "Baatein Ye Kabhi Na Tu Bhulna",
    genre: "pop",
    imgSrc:
      "https://songspk.ink/siteuploads/thumb/sft5/2123_resize2x_175x175.webp",
  },
  {
    artist: "arijit singh",
    src: "https://pagalnew.com/download128/2308",
    songName: "Muskurane",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft23/11147_4.jpg",
  },
  {
    artist: "arijit singh",
    src: "https://pagaliworld.com/files/download/id/11147",
    songName: "Enna Soa Kyu Rab Ne Banaya",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft32/15873_4.jpg",
  },
  {
    artist: "rahat fateh",
    src: "https://pagaliworld.com/siteuploads/thumb/sft33/16220_4.jpg",
    songName: "Tum Jo Aaye Zindagi Mein",
    genre: "classical",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft33/16220_4.jpg",
  },
  {
    artist: "rahat fateh",
    src: "https://pagaliworld.com/files/download/id/16135",
    songName: "Afreen Afreen",
    genre: "classical",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft33/16135_4.jpg",
  },
  {
    artist: "rahat fateh",
    src: "https://pagaliworld.com/files/download/id/15912",
    songName: "Surili Akhiyon Wale",
    genre: "classical",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft32/15912_4.jpg",
  },
  {
    artist: "rahat fateh",
    src: "https://pagaliworld.com/files/download/id/13777",
    songName: "Ishq Hai",
    genre: "classical",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft28/13777_4.jpg",
  },
  {
    artist: "rahat fateh",
    src: "https://pagaliworld.com/files/download/id/12967",
    songName: "Nit Khair Manga ",
    genre: "classical",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft26/12967_4.jpg",
  },
  {
    artist: "rahat fateh",
    src: "https://pagaliworld.com/files/download/id/12882",
    songName: "Kabhi Kabhi Ye Mujhe Sataye",
    genre: "classical",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft26/12882_4.jpg",
  },
  {
    artist: "rahat fateh",
    src: "https://pagaliworld.com/files/download/id/11784",
    songName: "Ye Kaisi Teri Khudgharzi ",
    genre: "classical",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft24/11784_4.jpg",
  },
  {
    artist: "rahat fateh",
    src: "https://pagaliworld.com/files/download/id/11777",
    songName: "Teri Meri Meri Teri",
    genre: "classical",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft24/11777_4.jpg",
  },
  {
    artist: "rahat fateh",
    src: "https://pagaliworld.com/files/download/id/9728",
    songName: "Tere Bin Nahi Lagda Dil Mera",
    genre: "classical",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft20/9728_4.jpg",
  },
  {
    artist: "rahat fateh",
    src: "https://pagaliworld.com/files/download/id/2297",
    songName: "Sanson Ki Mala",
    genre: "classical",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft5/2297_4.jpg",
  },
  {
    artist: "justin bieber",
    src: "https://pagaliworld.com/files/download/id/5697",
    songName: "Anyone",
    genre: "english",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft12/5697_4.jpg",
  },
  {
    artist: "justin bieber",
    src: "https://pagaliworld.com/files/download/id/4577",
    songName: "Peaches",
    genre: "english",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft10/4577_4.jpg",
  },
  {
    artist: "justin bieber",
    src: "https://pagaliworld.com/files/download/id/3743",
    songName: "Stay",
    genre: "english",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft8/3743_4.jpg",
  },
  {
    artist: "justin bieber",
    src: "https://pagaliworld.com/files/download/id/3509",
    songName: "Sorry",
    genre: "english",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft8/3509_4.jpg",
  },
  {
    artist: "justin bieber",
    src: "https://pagaliworld.com/files/download/id/3491",
    songName: "I Need You To Stay",
    genre: "english",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft7/3491_4.jpg",
  },
  {
    artist: "justin bieber",
    src: "https://pagaliworld.com/files/download/id/3383",
    songName: "Let Me Love You",
    genre: "english",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft7/3383_4.jpg",
  },
  {
    artist: "justin bieber",
    src: "https://pagaliworld.com/files/download/id/2469",
    songName: "Baby",
    genre: "english",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft5/2469_4.jpg",
  },
  {
    artist: "justin bieber",
    src: "https://pagaliworld.com/files/download/id/505",
    songName: "Intentions",
    genre: "english",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft2/505_4.jpg",
  },
  {
    artist: "Armaan Malik",
    src: "https://pagaliworld.com/files/download/id/16491",
    songName: "Raste Bhage Paon Se Aage",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft33/16491_4.jpg",
  },
  {
    artist: "Armaan Malik",
    src: "https://pagaliworld.com/files/download/id/16239",
    songName: "Danger Pilla ",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft33/16239_4.jpg",
  },
  {
    artist: "Armaan Malik",
    src: "https://pagaliworld.com/files/download/id/16193",
    songName: "Mai Dikhu Ya Na Dikhu",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft33/16193_4.jpg",
  },
  {
    artist: "Armaan Malik",
    src: "https://pagaliworld.com/files/download/id/16147",
    songName: "Agar Mna Ho To Rok Lena ",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft33/16147_4.jpg",
  },
  {
    artist: "Armaan Malik",
    src: "https://pagaliworld.com/files/download/id/15501",
    songName: "Jis Pal Tu Sath Mere",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft32/15501_4.jpg",
  },
  {
    artist: "Armaan Malik",
    src: "https://pagaliworld.com/files/download/id/14630",
    songName: "Wahi Toh Khuda Hai ",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft30/14630_4.jpg",
  },
  {
    artist: "Armaan Malik",
    src: "https://pagalnew.com/download128/4780",
    songName: "Main Hoon Hero Tera ",
    genre: "pop",
    imgSrc:
      "https://pagalnew.com/coverimages/Main-Hoon-Hero-Tera-Armaan-Malik-Version-Armaan-Malik-500-500.jpg",
  },
  {
    artist: "Armaan Malik",
    src: "https://pagaliworld.com/files/download/id/138",
    songName: "Chale Aana",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft1/138_4.jpg",
  },
  {
    artist: "Armaan Malik",
    src: "https://pagaliworld.com/files/download/id/9888",
    songName: "Yaara",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft20/9888_4.jpg",
  },
  {
    artist: "Armaan Malik",
    src: "https://pagaliworld.com/files/download/id/9720",
    songName: "Paathashala Loo",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft20/9720_4.jpg",
  },
  {
    artist: "asim azhar",
    src: "https://pagaliworld.com/files/download/id/16533",
    songName: "jo tu na mila mujhe",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft34/16533_4.jpg",
  },
  {
    artist: "asim azhar",
    src: "https://pagaliworld.com/files/download/id/15862",
    songName: "Man Tha Bara Tu Hota Mera",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft32/15862_4.jpg",
  },
  {
    artist: "asim azhar",
    src: "https://pagaliworld.com/files/download/id/12238",
    songName: "Jo Zakham Do To Mujhe",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft25/12238_4.jpg",
  },
  {
    artist: "asim azhar",
    src: "https://pagaliworld.com/files/download/id/11955",
    songName: "Ghalat Fehmi",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft24/11955_4.jpg",
  },
  {
    artist: "asim azhar",
    src: "https://pagaliworld.com/files/download/id/4940",
    songName: "Tarasti Hai Nigahen",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft10/4940_4.jpg",
  },
  {
    artist: "asim azhar",
    src: "https://pagaliworld.com/files/download/id/2437",
    songName: "Khelta Ja",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft5/2437_4.jpg",
  },
  {
    artist: "asrar",
    src: "https://ostpk.com/download/file.php?id=Mayi%20Ri%20OST%20Song%20Asrar%20Shah.mp3&yt=oVtYen6IREc",
    songName: "Mayi Ri",
    genre: "rock",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2023/08/Mayi-Ri-OST-Lyrics-Asrar-Shah-Wo-Lyrics.jpg",
  },
  {
    artist: "asrar",
    src: "https://ostpk.com/download/file.php?id=Ni%20Main%20Sadkay%20Song%20Asrar.mp3&yt=ZDn_aMj7Ybk",
    songName: "Ni Main Sadkay",
    genre: "rock",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/12/Ni-Main-Sadkay-Lyrics-Asrar-Wo-Lyrics.jpg",
  },
  {
    artist: "asrar",
    src: "https://ostpk.com/download/get.php?id=Parizaad-OST-Mp3-By-Asrar.mp3",
    songName: "Parizaad Drama OST",
    genre: "rock",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2021/10/Parizaad-Ost-Mp3-Download.jpg",
  },
  {
    artist: "asrar",
    src: "https://ostpk.com/download/file.php?id=Main%20Nara-e-Mastana%20(New%20Version)%20Bazm-e-Rang%20Chapter%202.mp3&yt=jU11bwiJl_8",
    songName: "Main Nara-e-Mastana",
    genre: "kalam",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/Nara-E-Mastana-Mp3-Song-Download-Abida-Parveen.jpg",
  },
  {
    artist: "abida parveen",
    src: "https://ostpk.com/download/file.php?id=Laghzish%20e%20Mastana%20Song%20Abida%20Parveen.mp3&yt=WEXbu2w5H1Q",
    songName: "Laghzish e Mastana",
    genre: "kalam",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2023/08/Laghzish-e-Mastana-Lyrics-Abida-Parveen-Shafqat-Amanat-Ali-Wo-Lyrics.jpg",
  },
  {
    artist: "abida parveen",
    src: "https://ostpk.com/download/file.php?id=Ali%20Azmat.mp3&yt=R24w5j9C2aA",
    songName: "Zinda Dil",
    genre: "pop",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2023/01/Zinda-Dil-Lyrics-Abida-Parveen-Ali-Azmat-Asim-Azhar-Atif-Aslam-Faakhir-Gul-Panra-Rahat-Fateh-Ali-Khan-Sahir-Ali-Bagga-Shafqat-Amanat-Ali-Wo-Lyrics.jpg",
  },
  {
    artist: "abida parveen",
    src: "https://ostpk.com/download/file.php?id=Koi%20Khamosh%20Song%20Abida%20Parveen.mp3&yt=UIsA2gGE9Kw",
    songName: "Koi Khamosh",
    genre: "kalam",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/09/Koi-Khamosh-Lyrics-Abida-Parveen-Wo-Lyrics.jpg",
  },
  {
    artist: "abida parveen",
    src: "Main Nara-e-Mastana",
    songName:
      "https://ostpk.com/download/file.php?id=Main%20Nara-e-Mastana%20(New%20Version)%20Bazm-e-Rang%20Chapter%202.mp3&yt=jU11bwiJl_8",
    genre: "kalam",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/Nara-E-Mastana-Mp3-Song-Download-Abida-Parveen.jpg",
  },
  {
    artist: "abida parveen",
    src: "https://ostpk.com/download/file.php?id=O%20Mere%20Maula%20Song%20Abida%20Parveen.mp3&yt=-WDG7XGzhf4",
    songName: "O Mere Maula",
    genre: "kalam",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/O-Mere-Maula-Mp3-Song-Download-Abida-Parveen.jpg",
  },
  {
    artist: "abida parveen",
    src: "https://ostpk.com/download/file.php?id=Tu%20Jhoom%20Song%20Coke%20Studio.mp3&yt=7D4vNcK6D38",
    songName: "Tu Jhoom",
    genre: "kalam",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/Tu-Jhoom-By-Coke-Studio-Mp3-Song-Download.jpg",
  },
  {
    artist: "azaan sami",
    src: "https://ostpk.com/download/file.php?id=Ik%20Vari%20Sun%20Le%20Song%20Azaan%20Sami%20Khan.mp3&yt=Z7ZdGwwj-LU",
    songName: "Ik Vari Sun Le ",
    genre: "love",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/Z7ZdGwwj-LU_maxres.jpg",
  },
  {
    artist: "azaan sami",
    src: "https://ostpk.com/download/file.php?id=Aashiqui%20Song%20Azaan%20Sami%20Khan.mp3&yt=9lNYhhdkrA8",
    songName: "Aashiqui ",
    genre: "sad",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/09/Aashiqui-Lyrics-Azaan-Sami-Khan-Wo-Lyrics.jpg",
  },
  {
    artist: "azaan sami",
    src: "https://ostpk.com/download/file.php?id=Ibadat%20Song%20Ost.mp3&yt=Bt-e0uUSDYU",
    songName: "Ibadat Song",
    genre: "sad",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/Ibadat-By-Ost-Mp3-Song-Download.jpg",
  },
  {
    artist: "azaan sami",
    src: "https://ostpk.com/download/file.php?id=TU%20Song%20Azaan%20Sami%20Khan.mp3&yt=skvBEZW3CeI",
    songName: "TU",
    genre: "party",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/TU-Mp3-Song-Download-Azaan-Sami-Khan.jpg",
  },
  {
    artist: "azaan sami",
    src: "https://ostpk.com/download/file.php?id=Ik%20Lamha%20Song%20Main%20Tera.mp3&yt=J7ck984Qhso",
    songName: "Ik Lamha",
    genre: "sad",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/Ik-Lamha-Mp3-Song-Download-Azaan-Sami-Khan.jpg",
  },
  {
    artist: "ali zafar",
    src: "https://ostpk.com/download/file.php?id=RAATI%20CHANN%20Song%20Ali%20Zafar.mp3&yt=JOkdttCRBdk",
    songName: "RAATI CHANN",
    genre: "pop",
    imgSrc: "https://i.dawn.com/primary/2016/07/5795ee61c07f1.jpg",
  },
  {
    artist: "ali zafar",
    src: "https://ostpk.com/download/file.php?id=Jhoom%20(Remix)%20Song%20Ali%20Zafar.mp3&yt=ikfjlvHHHHA",
    songName: "Jhoom",
    genre: "pop",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/11/Jhoom-Remix-Lyrics-Ali-Zafar-Wo-Lyrics.jpg",
  },
  {
    artist: "ali zafar",
    src: "https://ostpk.com/download/file.php?id=HUSN%20Song%20Ali%20Zafar.mp3&yt=EteUdcHMZHI",
    songName: "HUSN",
    genre: "love",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2023/06/HUSN-Lyrics-Ali-Zafar-Wo-Lyrics.jpg",
  },
  {
    artist: "ali zafar",
    src: "https://ostpk.com/download/file.php?id=Akhiyaan%20Song%20Ali%20Zafar.mp3&yt=puOT7TAIhSo",
    songName: "Akhiyaan",
    genre: "love",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/09/Akhiyaan-Lyrics-Ali-Zafar-Wo-Lyrics.jpg",
  },
  {
    artist: "ali zafar",
    src: "https://ostpk.com/download/file.php?id=Larsha%20Pekhawar%20Song%20Ali%20Zafar.mp3&yt=lh6Ltp5Ew9k",
    songName: "Larsha Pekhawar",
    genre: "party",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/1644766753_Larsha-Pekhawar-Ali-Zafar-ft-Gul-Panra-Fortitude.jpg",
  },
  {
    artist: "ali zafar",
    src: "https://ostpk.com/download/file.php?id=Is%20Pagal%20Si%20Mohabbat%20Song%20Ali%20Zafar.mp3&yt=scnryCQK1oU",
    songName: "Is Pagal Si Mohabbat",
    genre: "love",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/Is-Pagal-Si-Mohabbat-Mp3-Song-Download-Ali-Zafar-1.jpg",
  },
  {
    artist: "ali zafar",
    src: "https://ostpk.com/download/file.php?id=Dil%20Karey%20Song%20Quaid%20E%20Azam%20Zindabad.mp3&yt=VqIgAgy384A",
    songName: "Dil Karey",
    genre: "love",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/Dil-Karey-Mp3-Song-Download-Ali-Zafar.jpg",
  },
  {
    artist: "ali zafar",
    src: "https://ostpk.com/download/file.php?id=Jhoom%20Song%20Ali%20Zafar.mp3&yt=B4-HoKdW6j0",
    songName: "Jhoom",
    genre: "love",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/Jhoom-Mp3-Song-Download-Ali-Zafar.jpg",
  },
  {
    artist: "quratulain",
    src: "https://ostpk.com/download/file.php?id=Thagyan%20Song%20Coke%20Studio%20|%20Season%2014.mp3&yt=nNZvaMoiATE",
    songName: "Thagyan",
    genre: "sad",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/nNZvaMoiATE_maxres.jpg",
  },
  {
    artist: "quratulain",
    src: "https://ostpk.com/download/file.php?id=Qalandar.mp3&yt=1EtKQDDUQP8",
    songName: "Qalandar ",
    genre: "kalam",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2023/03/Qalandar-Lyrics-Quratulain-Balouch-Zain-Ali-Zohaib-Ali-Wo-Lyrics.jpg",
  },
  {
    artist: "quratulain",
    src: "https://ostpk.com/download/file.php?id=Wo%20Humsafar%20Tha%20OST%20Song%20Quratulain%20Balouch.mp3&yt=3TFFThFNE0Y",
    songName: "Wo Humsafar Tha",
    genre: "classical",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/Wo-Humsafar-Tha-OST-Mp3-Song-Download-Quratulain-Balouch.jpg",
  },
  {
    artist: "quratulain",
    src: "https://ostpk.com/download/file.php?id=Judai%20OST%20Song%20Quratulain%20Balouch.mp3&yt=SDkHK8rJZps",
    songName: "Judai ",
    genre: "sad",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/Judai-OST-Mp3-Song-Download-Quratulain-Balouch.jpg",
  },
  {
    artist: "quratulain",
    src: "https://ostpk.com/download/get.php?id=Yeh%20zindagi%20hai%20Ost%20Song%20Quratulain%20Balouch.mp3",
    songName: "Yeh zindagi hai",
    genre: "sad",
    imgSrc:
      "https://www.cokestudio.com.pk/season9/img/artists/Quratulain-Balouch.png",
  },
  {
    artist: "quratulain",
    src: "https://ostpk.com/download/file.php?id=Kaari%20Kaari%20Song%20Qurat-Ul-Ain%20Balouch.mp3&yt=rnlP77N61cA",
    songName: "Kaari Kaari ",
    genre: "sad",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2023/01/Kaari-Kaari-Lyrics-Qurat-Ul-Ain-Balouch-Wo-Lyrics.jpg",
  },
  {
    artist: "bilal saeed",
    src: "https://pagaliworld.com/files/download/id/3525",
    songName: "Mitti Da Khadona",
    genre: "sad",
    imgSrc:
      "https://cdns-images.dzcdn.net/images/artist/3b780adc271cec61f23f38ddffd67ffa/500x500.jpg",
  },
  {
    artist: "bilal saeed",
    src: "https://pagaliworld.com/files/download/id/9967",
    songName: "The Umbrella",
    genre: "party",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft20/9967_4.jpg",
  },
  {
    artist: "bilal saeed",
    src: "https://pagaliworld.com/files/download/id/7017",
    songName: "Khudaya Vey",
    genre: "sad",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft15/7017_4.jpg",
  },
  {
    artist: "bilal saeed",
    src: "https://pagaliworld.com/files/download/id/10657",
    songName: "Lambiya Judaiyan",
    genre: "sad",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/09/Lambiya-Judaiyan-Lyrics-Bilal-Saeed-Wo-Lyrics.jpg",
  },
  {
    artist: "bilal saeed",
    src: "https://pagaliworld.com/files/download/id/5920",
    songName: "Blah Blah Blah",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft12/5920_4.jpg",
  },
  {
    artist: "bilal saeed",
    src: "https://pagaliworld.com/files/download/id/6189",
    songName: "Beqarar Dil",
    genre: "sad",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft13/6189_4.jpg",
  },
  {
    artist: "bilal saeed",
    src: "https://pagaliworld.com/files/download/id/4630",
    songName: "adhi adhi raat",
    genre: "sad",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft10/4630_4.jpg",
  },
  {
    artist: "bilal saeed",
    src: "https://pagaliworld.com/files/download/id/2347",
    songName: "baari",
    genre: "pop",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft5/2347_4.jpg",
  },
  {
    artist: "bilal saeed",
    src: "https://pagaliworld.com/files/download/id/1597",
    songName: "Suroor",
    genre: "love",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft4/1597_4.jpg",
  },
  {
    artist: "bilal saeed",
    src: "https://pagaliworld.com/files/download/id/1513",
    songName: "qubool",
    genre: "love",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft4/1513_4.jpg",
  },
  {
    artist: "neha kakkar",
    src: "https://pagaliworld.com/files/download/id/16052",
    songName: "Dil Ko Karaar Aaya",
    genre: "love",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft33/16052_4.jpg",
  },
  {
    artist: "neha kakkar",
    src: "https://pagaliworld.com/files/download/id/15255",
    songName: "Balenciaga",
    genre: "party",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2023/06/Balenciaga-Lyrics-Neha-Kakkar-Priyanka-Ahuja-Tony-Jr.-Tony-Kakkar-Wo-Lyrics.jpg",
  },
  {
    artist: "neha kakkar",
    src: "https://pagaliworld.com/files/download/id/14961",
    songName: "Akhiyan Farebi Shaitani Hai",
    genre: "love",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft30/14961_4.jpg",
  },
  {
    artist: "neha kakkar",
    src: "https://pagaliworld.com/files/download/id/14869",
    songName: "Kar Gayi Chull ",
    genre: "party",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2023/01/Kar-Gayi-Chull-Lyrics-Badshah-Fazilpuria-Neha-Kakkar-Sukriti-Kakar-Wo-Lyrics.jpg",
  },
  {
    artist: "neha kakkar",
    src: "https://pagaliworld.com/files/download/id/14804",
    songName: "o saki saki",
    genre: "party",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/08/O-Saki-Saki-Mp3-Song-Download-B-Praak.jpg",
  },
  {
    artist: "neha kakkar",
    src: "https://pagaliworld.com/files/download/id/14323",
    songName: "massla",
    genre: "pop",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2023/04/Massla-Lyrics-Neha-Kakkar-Singhsta-Wo-Lyrics.jpg",
  },
  {
    artist: "neha kakkar",
    src: "https://pagaliworld.com/files/download/id/13826",
    songName: "daiyya daiyya",
    genre: "party",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2023/03/Daiyya-Daiyya-Lyrics-Neha-Kakkar-Wo-Lyrics.jpg",
  },
  {
    artist: "neha kakkar",
    src: "https://pagaliworld.com/files/download/id/11011",
    songName: "bijli",
    genre: "party",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft23/11011_4.jpg",
  },
  {
    artist: "neha kakkar",
    src: "https://pagaliworld.com/files/download/id/10742",
    songName: "12 ladke",
    genre: "party",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2022/11/12-Ladke-Lyrics-Neha-Kakkar-Tony-Kakkar-Wo-Lyrics.jpg",
  },
  {
    artist: "neha kakkar",
    src: "https://pagaliworld.com/files/download/id/768",
    songName: "moscow suka",
    genre: "party",
    imgSrc: "https://pagaliworld.com/siteuploads/thumb/sft2/768_4.jpg",
  },
  {
    artist: "young desi",
    src: "https://pagaliworld.com/files/download/id/15024",
    songName: "senorita",
    genre: "love",
    imgSrc:
      "https://ostpk.com/wp-content/uploads/2023/05/Senorita-Lyrics-Tony-Kakkar-Young-Desi-Wo-Lyrics.jpg",
  },
  {
    artist: "young desi",
    src: "",
    songName: "",
    genre: "love",
    imgSrc: "",
  },
  {
    artist: "young desi",
    src: "",
    songName: "",
    genre: "love",
    imgSrc: "",
  },
  {
    artist: "young desi",
    src: "",
    songName: "",
    genre: "love",
    imgSrc: "",
  },
  {
    artist: "young desi",
    src: "",
    songName: "",
    genre: "love",
    imgSrc: "",
  },
  {
    artist: "young desi",
    src: "",
    songName: "",
    genre: "love",
    imgSrc: "",
  },
  {
    artist: "young desi",
    src: "",
    songName: "",
    genre: "love",
    imgSrc: "",
  },
  {
    artist: "young desi",
    src: "",
    songName: "",
    genre: "love",
    imgSrc: "",
  },
  {
    artist: "young desi",
    src: "",
    songName: "",
    genre: "love",
    imgSrc: "",
  },
  {
    artist: "young desi",
    src: "",
    songName: "",
    genre: "love",
    imgSrc: "",
  },
];

export default SongsData;
